modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "Custom"

[[mods]]
modId = "biomemakeover"
version = "${version}"
displayName = "Biome Makeover"
authors = "LASERKNIGHTS"
description = '''
Biome Makeover is a mod designed to update vanilla's biomes.
'''
logoFile = "bm-logo.png"

[[dependencies.biomemakeover]]
modId = "forge"
mandatory = true
versionRange = "[39.0.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomemakeover]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.biomemakeover]]
modId = "architectury"
mandatory = true
versionRange = "[4.0.30,)"
ordering = "AFTER"
side = "BOTH"